model = "qwen3-vl:8b"
output_filename_template = "{{file_basename}}.md"
prompt = """###
Context (the last few lines of markdown from the previous page):
{context}
###
Convert the image to formatted markdown:
- When it is unclear what an image is, don't output anything for it.
- Every piece of math MUST be wrapped in single '$' delimiters: $equation$.
    - DO NOT put whitespace between the '$' delimiters and the math characters inside.
    - Correct: $math$
    - Wrong: $ math $
- If you encounter a hand-drawn diagram, flowchart, or structural schematic, convert it into a valid code block wrapped in a ```mermaid syntax at its exact relative position on the page.
    - Do not skip the text before or after the diagram.
- Do not wrap text in codeblocks.
"""
template = """
{{llm_output}}
"""
